spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

weather.api.key=${WEATHER_API_KEY}
weather.api.base-url=https://api.openweathermap.org/data/2.5
logging.config=classpath:logback-spring.xml
logging.file.path=logs
app.cors.allowed-origins=http://localhost:4200

# ? Flyway lo manejamos manualmente en el Bean
spring.flyway.enabled=false